### ISSUE TITLE
Practica 2 Usabilidad de una interfaz

### ISSUE THREAD

**Issue by EvelynLopezz** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-los-3-mosqueteros-topicos#2]
[Calculadora Evelyn,Melissa,Samuel.zip](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-los-3-mosqueteros-topicos/files/8178350/Calculadora.Evelyn.Melissa.Samuel.zip)

[Reporte Interfaz gráfica en Visual Studio  (1).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-los-3-mosqueteros-topicos/files/8178351/Reporte.Interfaz.grafica.en.Visual.Studio.1.pdf)

**Comment by josealfredo79** [comment]
@EvelynLopezz Falta la calificación

**Comment by magaly1311** [comment]
16% calificación de la practica2

**Comment by josealfredo79** [comment]
Bien hecho y revisado
